baseURL = "https://example.org/"
languageCode = "en-us"
title = "Bobby Hendricks"
theme = "PaperMod"

[params]
  description = "Data Science & Data Engineering Portfolio"

  [params.profileMode]
    enabled = true
    title = "Bobby Hendricks"
    subtitle = "Data Scientist & Data Engineer"

    [[params.profileMode.buttons]]
      name = "Projects"
      url = "/projects/"
    [[params.profileMode.buttons]]
      name = "Experience"
      url = "/experience/"
    [[params.profileMode.buttons]]
      name = "Resume"
      url = "/resume/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/CHbobray11"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bobby-h-143113252/"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:bobbyhendricks2029@u.northwestern.edu"

[menu]
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 10
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    name = "Skills"
    url = "/skills/"
    weight = 30
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 40